revoke execute on function public.admin_assign_rider(uuid, uuid) from public, anon;
revoke execute on function public.admin_create_rider(uuid, text, text, text, boolean) from public, anon;
revoke execute on function public.admin_create_vendor(uuid, text, text, boolean, text, numeric, numeric, numeric) from public, anon;
revoke execute on function public.admin_set_rider_suspension(uuid, boolean) from public, anon;
revoke execute on function public.admin_set_vendor_suspension(uuid, boolean) from public, anon;
revoke execute on function public.admin_update_product(uuid, boolean) from public, anon;
revoke execute on function public.advance_rider_order_status(uuid, text) from public, anon;
revoke execute on function public.advance_vendor_order_status(uuid, text) from public, anon;
revoke execute on function public.customer_delete_address(uuid) from public, anon;
revoke execute on function public.customer_set_default_address(uuid) from public, anon;
revoke execute on function public.customer_submit_order_review(uuid, integer, integer, integer, text) from public, anon;
revoke execute on function public.customer_submit_product_review(uuid, uuid, integer, text) from public, anon;
revoke execute on function public.handle_new_user() from public, anon;
revoke execute on function public.is_admin() from public, anon;
revoke execute on function public.rider_set_availability(boolean) from public, anon;
revoke execute on function public.set_vendor_store_status(boolean) from public, anon;
revoke execute on function public.sync_rider_location_feed() from public, anon;
revoke execute on function public.vendor_update_product(uuid, text, numeric, text, integer, text, text, text, boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean) from public, anon;
